# Generated by Django 5.1.1 on 2024-09-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_author_form_genre_publishing_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_name', models.TextField(verbose_name='Форма написания')),
            ],
            options={
                'verbose_name': 'Род литературы',
                'verbose_name_plural': 'Роды литературы',
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_title', models.TextField(verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Вид содержания',
                'verbose_name_plural': 'Виды содержания',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.kind'),
        ),
        migrations.AddField(
            model_name='book',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.matter'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
