# Generated by Django 5.1.1 on 2024-09-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_kind_matter_remove_book_genre_book_kind_book_matter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_patronymic',
            field=models.TextField(verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_surname',
            field=models.TextField(verbose_name='Фамилия'),
        ),
    ]
