# Generated by Django 5.1 on 2024-10-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_author_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_patronymic',
            new_name='patronymic',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_years_of_life',
            new_name='years_of_life',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='form_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='kind',
            old_name='kind_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='matter',
            old_name='matter_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='publishing_house',
            old_name='house_name',
            new_name='name',
        ),
    ]
