# Generated by Django 5.1 on 2024-11-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_rename_publishing_house_publishinghouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(null=True, upload_to='books', verbose_name='Изображение'),
        ),
    ]
