# Generated by Django 5.1 on 2024-11-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_book_picture_author_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishinghouse',
            name='picture',
            field=models.ImageField(null=True, upload_to='publishingHouse', verbose_name='Изображение'),
        ),
    ]
