# Generated by Django 5.1 on 2024-12-10 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_book_user_form_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='form',
        ),
        migrations.RemoveField(
            model_name='book',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='book',
            name='matter',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishingHouse',
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='book',
            name='form_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.form', verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='book',
            name='kind_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.kind', verbose_name='Род'),
        ),
        migrations.AddField(
            model_name='book',
            name='matter_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.matter', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishingHouse_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.publishinghouse', verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='kind',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='matter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='publishinghouse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='picture',
            field=models.ImageField(null=True, upload_to='publishingHouses', verbose_name='Изображение'),
        ),
    ]
